select
DATETIME,
SUM(COUNTER_1_BIN) BIN_1,
SUM(COUNTER_2_BIN) BIN_2,
SUM(COUNTER_3_BIN) BIN_3,
SUM(COUNTER_4_BIN) BIN_4,
SUM(COUNTER_5_BIN) BIN_5,
SUM(COUNTER_6_BIN) BIN_6,
SUM(COUNTER_7_BIN) BIN_7,
SUM(COUNTER_8_BIN) BIN_8,
SUM(COUNTER_9_BIN) BIN_9,
SUM(COUNTER_10_BIN) BIN_10,
SUM(COUNTER_11_BIN) BIN_11,
SUM(COUNTER_12_BIN) BIN_12,
SUM(COUNTER_13_BIN) BIN_13,
SUM(COUNTER_14_BIN) BIN_14

from counter_table

where DATETIME > :FILTER_1 and DATETIME < :FILTER_2
group by DATETIME
order by DATETIME